version: "3.9"
services:
  master-api:
    build: ./master-service/gateway
    ports: [ "8080:80" ]

  master-ui:
    build: ./master-service/ui_dashboard
    ports: [ "7860:7860" ]

  image-classifier:
    build: ./repo-image-classifier
    ports: [ "8001:80" ]

  sentiment-analysis:
    build: ./repo-sentiment
    ports: [ "8002:80" ]
